//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 06:43:36 PM IST 
//


package com.soapcoursemanagement.coursedetails;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soapcoursemanagement.coursedetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soapcoursemanagement.coursedetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FetchAllCourseDetailsRequest }
     * 
     */
    public FetchAllCourseDetailsRequest createFetchAllCourseDetailsRequest() {
        return new FetchAllCourseDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteCourseDetailsRequest }
     * 
     */
    public DeleteCourseDetailsRequest createDeleteCourseDetailsRequest() {
        return new DeleteCourseDetailsRequest();
    }

    /**
     * Create an instance of {@link FetchAllCourseDetailsResponse }
     * 
     */
    public FetchAllCourseDetailsResponse createFetchAllCourseDetailsResponse() {
        return new FetchAllCourseDetailsResponse();
    }

    /**
     * Create an instance of {@link CourseDetails }
     * 
     */
    public CourseDetails createCourseDetails() {
        return new CourseDetails();
    }

    /**
     * Create an instance of {@link FetchCourseDetailsResponse }
     * 
     */
    public FetchCourseDetailsResponse createFetchCourseDetailsResponse() {
        return new FetchCourseDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteCourseDetailsResponse }
     * 
     */
    public DeleteCourseDetailsResponse createDeleteCourseDetailsResponse() {
        return new DeleteCourseDetailsResponse();
    }

    /**
     * Create an instance of {@link FetchCourseDetailsRequest }
     * 
     */
    public FetchCourseDetailsRequest createFetchCourseDetailsRequest() {
        return new FetchCourseDetailsRequest();
    }

}
